version: '3.1'

services:
  master-db-service:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: Aj189628@
      POSTGRES_USER: janny
    ports:
      - 5556:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data

  mongo-db-service:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: janny
      MONGO_INITDB_ROOT_PASSWORD: Aj189628@
      MONGO_INITDB_DATABASE: catelogue-service  # This is the initial database name
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  skd-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:5100"
    environment:
      DATABASE_URL: postgres://janny:Aj189628@@master-db-service:5556/skd-auth-service
      PORT: 5100
      JWT_SECRET: Aj189628@
      PASS_SECRET: Aj189628@
    depends_on:
      - master-db-service

  skd-master-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3110:5110"
    environment:
      DATABASE_URL: postgres://janny:Aj189628@@master-db-service:5556/skd-master-service
      PORT: 5110
      JWT_SECRET: Aj189628@
      PASS_SECRET: Aj189628@
    depends_on:
      - master-db-service


volumes:
  timescale_data:
  mongodb_data:
